### ISSUE TITLE
Issue after updating Xcode and sdk

### ISSUE THREAD

**Issue by AsimmParvezz** [Mastercard/masterpass-qr-scan-sdk-ios#2]
Hi,

I am getting the following error after updating to Xcode 9:
"dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
Referenced from: /Users/....../Containers/Bundle/Application/ACDFA853-ADD4-4C1D-A45B-408678E75DD7/my.app/Frameworks/MasterpassQRScanSDK.framework/MasterpassQRScanSDK
  Reason: image not found"

Is this because of Swift 4 or some related update.  Please help in this regard.

Regards.

**Comment by chozinul** [comment]
Hi Asimm,

For Objective-C, go to your Xcode project's **Build Settings** and set **Always Embed Swift Standard Libraries** to **YES**

-Amri-

**Comment by AsimmParvezz** [comment]
Hi I have already set the Always Embed Swift Standard Libraries to YES

**Comment by chozinul** [comment]
Can you use our updated SDK instead? It support swift 4 and xcode 9.

pod 'MasterpassQRScanSDK', '~> 1.0.7'

**Comment by AsimmParvezz** [comment]
Hi thanks it works with the new pod Version.
Thankyou :)
