### ISSUE TITLE
Cannot archive 

### ISSUE THREAD

**Issue by ShehanMadushanka** [Mastercard/masterpass-qr-scan-sdk-ios#3]
When archiving this error has occurred.

XCode 10.2

bitcode bundle could not be generated because /MPQRScanSDK.framework/MPQRScanSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/MPQRScanSDK.framework/MPQRScanSDK' for architecture arm64

**Comment by AliMehmood** [comment]
facing the same problem with MPQRCoreSDK

**Comment by tiwareep** [comment]
Please contact payment_application@mastercard.com to get your issues resolved.
