### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by raghu-gislen** [Mastercard/masterpass-qr-scan-sdk-ios#4]
Hi,

1. Is it possible to get the full source code for this extension to QRCodeReaderViewController?
2. Under what license is this distributed? 
3. I hope that you will also release the source and uphold the spirit of Free and Open Software, as providing the source encourages and enables others to improve and contribute. The original is under MIT license rather than GPL, which is a pity

**Comment by tiwareep** [comment]
Hi, 

Please contact payment_application@mastercard.com to check if this are able to obtain the full source code.
